procedure_test: False
use_eeg: True

# main visual parameters
screen_color: grey
text_color: black
text_size: 28

stimulus_size: 50
stimulus_separator_size: 30
stimulus_color: black
stimulus_dist: [-30, 0, 30]
stimulus_pos: [0, 150]

answers_size: 50
answers_separator_size: 30
answers_color: black
answers_dist: [-30, 0, 30]
answers_pos: [[-225, -50], [-75, -50], [75, -50], [225, -50]]


# stimulus
stimulus_type: image # image or text
stimulus_list: [1_8.png, 3_8.png, 7_8.png, 2_8.png]
separators: {equal: "|", higher: /, lower: \}

# reactions
reaction_keys: [num_1, num_2, num_3, num_enter]

# time parameters
answer_time: 10

# training
do_training: True
fdbk_training: True
training_trials: {easy: 2, hard: 2, control: 2}


# experiment
fdbk_experiment: False
experiment_trials: {easy: 25, hard: 25, control: 25}


# fixation point
fixation_size: 56
fixation_color: black
fixation_text: +
fixation_time: 2
fixation_pos: [0, 0]


# feedback
fdbk_correct: Poprawna odpoweidź
fdbk_incorrect: Błędna odpowiedź
fdbk_no_answer: Brak odpowiedzi
fdbk_show_time: 2
fdbk_color: black
fdbk_size: 30

# wait
wait_time: 1.5
wait_jitter: 1


# show extra text during trial
extra_text_to_show: [{pos: [-225, -90], color: darkgrey, size: 20, text: "1"},
                     {pos: [-75, -90], color: darkgrey, size: 20, text: "2"},
                     {pos: [75, -90], color: darkgrey, size: 20, text: "3"},
                     {pos: [225, -90], color: darkgrey, size: 20, text: "enter"}]

# clock
show_clock: false
clock_pos: [450, 350]
clock_size: 60
clock_show_time: 7

# timer
show_timer: false
timer_pos: [600, 350]
timer_color: black
timer_size: 60
